import { Poppins, Bebas_Neue } from "next/font/google";
import "./globals.css";

const bebas = Bebas_Neue({
  variable: "--title",
  subsets: ["latin"],
  weight: "400",
});
const poppins = Poppins({
  variable: "--poppins",
  weight: ["400", "700"],
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${poppins.variable}  ${bebas.variable} antialiased`}>
        <div className="grid gap-14 p-14 ">{children}</div>
      </body>
    </html>
  );
}
